/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeSwitch: (typeof import('./../src/components/Common/DarkModeSwitch.vue'))['default'];
    HelloWorld: (typeof import('./../src/components/HelloWorld.vue'))['default'];
    NaiveProvider: (typeof import('./../src/components/Common/NaiveProvider.vue'))['default'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCheckbox: (typeof import('naive-ui'))['NCheckbox'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NFormItem: (typeof import('naive-ui'))['NFormItem'];
    NGradientText: (typeof import('naive-ui'))['NGradientText'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NSpace: (typeof import('naive-ui'))['NSpace'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SystemLogo: (typeof import('./../src/components/Common/SystemLogo.vue'))['default'];
  }
}
