/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Action: (typeof import('./../src/components/Table/components/Action.vue'))['default'];
    ApiSelect: (typeof import('./../src/components/Form/components/ApiSelect.vue'))['default'];
    ApiTree: (typeof import('./../src/components/Form/components/ApiTree.vue'))['default'];
    ApiTreeSelect: (typeof import('./../src/components/Form/components/ApiTreeSelect.vue'))['default'];
    AutoComplete: (typeof import('./../src/components/Form/components/AutoComplete.vue'))['default'];
    DarkModeContainer: (typeof import('./../src/components/Common/DarkModeContainer.vue'))['default'];
    DarkModeSwitch: (typeof import('./../src/components/Common/DarkModeSwitch.vue'))['default'];
    Descriptions: (typeof import('./../src/components/Descriptions/index.vue'))['default'];
    Form: (typeof import('./../src/components/Form/index.vue'))['default'];
    FormAction: (typeof import('./../src/components/Form/components/FormAction.vue'))['default'];
    FormItemComponent: (typeof import('./../src/components/Form/components/FormItemComponent.vue'))['default'];
    HoverContainer: (typeof import('./../src/components/Common/HoverContainer.vue'))['default'];
    IconPicker: (typeof import('./../src/components/Form/components/IconPicker.vue'))['default'];
    Modal: (typeof import('./../src/components/Modal/index.vue'))['default'];
    NaiveProvider: (typeof import('./../src/components/Common/NaiveProvider.vue'))['default'];
    NAvatar: (typeof import('naive-ui'))['NAvatar'];
    NBackTop: (typeof import('naive-ui'))['NBackTop'];
    NBreadcrumb: (typeof import('naive-ui'))['NBreadcrumb'];
    NBreadcrumbItem: (typeof import('naive-ui'))['NBreadcrumbItem'];
    NButton: (typeof import('naive-ui'))['NButton'];
    NCard: (typeof import('naive-ui'))['NCard'];
    NCheckbox: (typeof import('naive-ui'))['NCheckbox'];
    NColorPicker: (typeof import('naive-ui'))['NColorPicker'];
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider'];
    NDialogProvider: (typeof import('naive-ui'))['NDialogProvider'];
    NDivider: (typeof import('naive-ui'))['NDivider'];
    NDrawer: (typeof import('naive-ui'))['NDrawer'];
    NDrawerContent: (typeof import('naive-ui'))['NDrawerContent'];
    NDropdown: (typeof import('naive-ui'))['NDropdown'];
    NForm: (typeof import('naive-ui'))['NForm'];
    NFormItem: (typeof import('naive-ui'))['NFormItem'];
    NGradientText: (typeof import('naive-ui'))['NGradientText'];
    NGrid: (typeof import('naive-ui'))['NGrid'];
    NGridItem: (typeof import('naive-ui'))['NGridItem'];
    NImage: (typeof import('naive-ui'))['NImage'];
    NInput: (typeof import('naive-ui'))['NInput'];
    NInputNumber: (typeof import('naive-ui'))['NInputNumber'];
    NLayout: (typeof import('naive-ui'))['NLayout'];
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent'];
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader'];
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider'];
    NLoadingBarProvider: (typeof import('naive-ui'))['NLoadingBarProvider'];
    NMenu: (typeof import('naive-ui'))['NMenu'];
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider'];
    NModal: (typeof import('naive-ui'))['NModal'];
    NNotificationProvider: (typeof import('naive-ui'))['NNotificationProvider'];
    NScrollbar: (typeof import('naive-ui'))['NScrollbar'];
    NSelect: (typeof import('naive-ui'))['NSelect'];
    NSpace: (typeof import('naive-ui'))['NSpace'];
    NSwitch: (typeof import('naive-ui'))['NSwitch'];
    NTabPane: (typeof import('naive-ui'))['NTabPane'];
    NTabs: (typeof import('naive-ui'))['NTabs'];
    NTooltip: (typeof import('naive-ui'))['NTooltip'];
    RadioGroup: (typeof import('./../src/components/Form/components/RadioGroup.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SelectPicker: (typeof import('./../src/components/Form/components/SelectPicker.vue'))['default'];
    SystemLogo: (typeof import('./../src/components/Common/SystemLogo.vue'))['default'];
    Table: (typeof import('./../src/components/Table/index.vue'))['default'];
    Toolbars: (typeof import('./../src/components/Table/components/Toolbars.vue'))['default'];
    Upload: (typeof import('./../src/components/Form/components/Upload.vue'))['default'];
  }
}
